### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by Rummskartoffel** [tridactyl/native_messenger#10]
The native messenger itself reports version 0.2.0, while the release and the version file on the main repo say 0.0.2. The former would make more sense, since the latest version of the old messenger is 0.1.11. I would've just made a PR, but I don't know how to change that with GitHub Actions involved.

**Comment by bovine3dom** [comment]
`0.2.0` will be the first Nim native messenger.

0.0.1 and 0.0.2 are just tags I made to test out GitHub releases. I'm hoping I can delete them once we're done.

I put 0.0.2 in that file so that the tag would point to a real file.

(For future reference, just do `git tag x.x.x && git push --tags` on your PR branch.)

I'm not 100% sure I can delete or change releases once they're released, so I don't want to make a 0.2.0 until I'm reasonably happy with it.

This is mostly because I know there will be loads of issues with it and I don't want to end up with version 0.2.99 being the first version that works. So, vanity, really.
