### ISSUE TITLE
`run` on Windows appears to escape quotes

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/native_messenger#18]
_Originally posted by @vadz in https://github.com/tridactyl/tridactyl/issues/876#issuecomment-766111592_

There seems to be something wrong with command line parsing: my `editorcmd` is `gvim.exe -f -c "se ft=markdown wrap lbr tw=0" %f` and it worked fine with 0.1.10 before, but now it starts editing the file called `ft=markdown` and a few more because the quotes get escaped and I couldn't find any way to prevent this from happening (other than removing `-c ...` entirely). Would you have any idea about this by chance? TIA!

---

https://github.com/tridactyl/native_messenger/blob/100198fb4c1e5167ad59d310c93d4d3ef8e77ee8/src/native_main.nim#L108

**Comment by bovine3dom** [comment]
Shouldn't make a Windows release until this is fixed as it will probably break lots of things

**Comment by Rummskartoffel** [comment]
I was afraid something like this would happen. I *presume* – but I'm not sure – that `startProcess` wraps each argument in quotes, so `gvim.exe -f -c "se ft=markdown wrap lbr tw=0" %f` becomes `cmd "/c" "gvim.exe -f -c "se ft=markdown wrap lbr tw=0" %f"`, which cmd interprets to run the program `gvim.exe -f -c se` with arguments `ft=markdown`, `wrap`, `lbr`, `tw=0 %f` or something of the sort, which makes no sense.
I'm not sure what we can actually *do* about this, though. We could get normal quoting behaviour if we got rid of the "cmd" call, but then we'd lose built-ins again. I still don't really want to believe Nim doesn't have a native way to run commands in a proper shell on Windows, though.

However, I don't remember if the version I tested where I noticed that I couldn't use built-ins used `poEvalCommand`. I'm assuming it had, because all the fuss about getting commands to run in cmd would've been really stupid otherwise, but on the other hand [the documentation](https://nim-lang.org/docs/osproc.html#startProcess,string,string,openArray[string],StringTableRef,set[ProcessOption]) literally states:
> `poEvalCommand` [...] uses the system shell to run the specified command

So it really *should* work.
I can test that again sometime, but it might be a while. Right now I'm fighting `:restart` and losing – I finally got the motivation to try and tackle it – and I don't want to get too distracted.

**Comment by bovine3dom** [comment]
I'm pretty sure we were using poEvalCommand.

There's really no rush with any of this - some of the issues we are fixing are ~2.5 years old. Please don't feel obligated to do anything : )

**Comment by vadz** [comment]
Using `cmd` under MSW seems inconsistent with the Unix version, which doesn't use shell, so I think removing it would be the right thing to do.

**Comment by Rummskartoffel** [comment]
_Maybe_ `os.quoteShell` or `os.quoteShellCommand` is what we need here, but I haven't tried that yet, either.

**Comment by bovine3dom** [comment]
If Nim is "helpfully" quoting stuff without `poEvalCommand`, a daft fix would be to use `poEvalCommand` but prefix the command with "cmd /c"
