### ISSUE TITLE
Work out how to distribute binary to end users

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/native_messenger#3]
I think we're just going to have to replace the install scripts with some new ones - https://github.com/tridactyl/tridactyl/blob/21d18025a1308221d2869c13c65c34f335ec44f2/native/install.sh#L23 and https://github.com/tridactyl/tridactyl/blob/21d18025a1308221d2869c13c65c34f335ec44f2/native/win_install.ps1#L1

since we now need to determine OS, mark the file as executable and bypass the new OSX signing requirements.

(Edit: the signing stuff means that we can't update the OSX native messenger without the user intervening - but I'm not sure it ever worked on OSX anyway? We should at least make sure that we don't break the messenger by trying to update it).

We no longer need to determine if Python 3 is installed so the `win_install` script can probably become a bit simpler.

---

For simplicity, the new install scripts should live on the Tridactyl repository so that the current trick of using the repository as it stood at the time that that version of Tridactyl was released can still be employed. Those scripts should then hard-code the tag of the release that they download.

**Comment by Rummskartoffel** [comment]
I'd be willing to take a shot at the Windows install script.

**Comment by bovine3dom** [comment]
I think probably the easiest way to do it is to keep the native messenger version in a new file on the Tridactyl repo, so that

`tridactyl/master/native/install.sh TAG` executes

1. Read `tridactyl/tag/nativeversion.txt`
2. Download `native_messenger/nativeversion/native_main.py`

I think anything else would be too complicated or break backwards compatibility.

**Comment by bovine3dom** [comment]
It should be simple to download the releases: `https://github.com/tridactyl/native_messenger/releases/download/[tag]/native_main-{Windows, macOS, Linux}` 

e.g.

`https://github.com/tridactyl/native_messenger/releases/download/0.0.2/native_main-Windows`

We'll need to have platform specific manifests + make sure the scripts download the binary for the right platform.

**Comment by Rummskartoffel** [comment]
Sounds good to me! I was going to suggest breaking backwards compatibility anyway, because the current Windows install script feels really overcomplicated and the code is nigh-unreadable. Now that you've made a release and I know what they look like, I should be able to get the new Windows installer mostly done today.
Only thing I still need is the exact format and path of the version file in the main repo. Could you write that and push it to tridactyl/tridactyl#3163 so I can test against it?

**Comment by bovine3dom** [comment]
Done: https://github.com/tridactyl/tridactyl/blob/752bd49ded8e3b2ae426cdca57de86673d5bc9c7/native/current_native_version#L1

Manifests - yes.

**Comment by Rummskartoffel** [comment]
The installing part of the Windows installer is pretty much ready now. I still need to do the uninstaller – which, by the way, I think we should add an excmd for, because till now the process of uninstalling would've been to manually download the installer script, then call it in Powershell with `-Uninstall`, which isn't all that user-friendly. I think it'd be good to have a one-liner like for installing, and maybe we could additionally leave a copy of the installer lying in the native messenger's directory, for greater ease of manual use.

**Comment by bovine3dom** [comment]
I didn't realise there even was an uninstall script. Yeah, `nativeuninstall` makes sense, but then I'd have to add it to the shell scripts too and they're already big and horrible enough that I'm regretting having to rewrite them.

While I'm thinking about it, we can bin the win_installcmd and instead use platform specific defaults. They're near the top of lib/config.ts IIRC

**Comment by Rummskartoffel** [comment]
I mean, we could always just make that command just display instructions on how to remove the native messenger. Would still be better than how it currently is – because if we have any documentation on that, I haven't been able to find it, at least.
On Windows, it should be pretty easy to do, though, so I'm just gonna implement it in the script so the possibility is there, at least.

**Comment by bovine3dom** [comment]
I think it's as simple as deleting the manifest. The messenger can be deleted too to keep things tidy.

**Comment by bovine3dom** [comment]
On migration from the old messenger: we should see what happens if the manifest is replaced while Tridactyl is running.

**Comment by Rummskartoffel** [comment]
I just tried it out on Windows 10 and it starts using the new messenger immediately. I'm guessing Firefox checks the manifest every time it tries to invoke the messenger.

**Comment by bovine3dom** [comment]
I think this is pretty much done? I haven't bothered with "uninstall" but I think that doesn't matter given that we've had it for ~3 years and no-one has ever asked : )
