### ISSUE TITLE
`:updatenative` doesn't work from Nim-to-Nim

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/native_messenger#34]
Broken on both Windows and Linux (presumably OSX too).

**Comment by Rummskartoffel** [comment]
On Windows, the problem is twofold:
1. Quoting rules have subtly changed from the Python messenger.
2. We can't overwrite the native messenger while it is running.

(1) only requires slight changes to the current install command. They may well even be compatible with the old messenger.

(2) requires us to invoke the install command, then exit the messenger before it is finished, so that the binary can be replaced. For invoking the command, we can re-use `:restart` code to prevent the script being killed by Firefox. The install script itself just needs to run a loop with a handful of iterations, trying each time to overwrite the binary and sleeping a short while if it fails. If it fails too often, it just exits.

P.S.: Updating has been broken on OS X [for a while](https://github.com/tridactyl/tridactyl/commit/88e429ae926d916677133baeddb6bc571cbf3112).

**Comment by bovine3dom** [comment]
Fixed in #35
