### ISSUE TITLE
Reimplement win_firefox_restart

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/native_messenger#5]
It's a pretty big beast.

https://github.com/tridactyl/tridactyl/blob/ede89e683ad880a5bce79278f45737a64bf9a1e2/native/native_main.py#L155

**Comment by Rummskartoffel** [comment]
I would've said we could just use `native.ff_cmdline`, which I tried to fix a few days ago – and it did work at the time –, but apparently (and somewhat unsurprisingly, considering the hacky implementation) that's broken again. It's pretty mysterious – `await tri.native.ff_cmdline()` returns `undefined`, while copying the Powershell command string from native.ts and manually using it with `tri.native.run` works just as it should.
But just in case I ever get that to work 100% of the time, it should make implementing `:restart` trivial.

**Comment by bovine3dom** [comment]
I think most of that code is concerned with scheduling a task to restart Firefox rather than working out what arguments it was called with.

I think it might be because Windows kills the native process when Firefox exits, which other OSs don't do. But my memory is very hazy on this : )

**Comment by Rummskartoffel** [comment]
Yeah, looks like it does. Bah.

**Comment by bovine3dom** [comment]
Perhaps we can do it more cleanly with the `winlean` module?

**Comment by Rummskartoffel** [comment]
I can't immediately think of a good way to do it... I guess what might work quite nicely would be to spawn another instance of the native messenger to which we pass the desired Firefox invocation. We'd have to spawn it using `CreateProcessW` with [`CREATE_BREAKAWAY_FROM_JOB`](https://docs.microsoft.com/en-gb/windows/win32/procthread/process-creation-flags?redirectedfrom=MSDN#CREATE_BREAKAWAY_FROM_JOB), because Firefox [kills all the processes in the native messenger's Job](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging#closing_the_native_app). This second instance could then wait for Firefox – or maybe just the first messenger – to terminate and restart Firefox after that. I'm not sure how/whether we can wait on a process that isn't a child, though.

**Comment by cmcaine** [comment]
You can get the parent process ID (
https://gist.github.com/mattn/253013/d47b90159cf8ffa4d92448614b748aa1d235ebe4
), use that to create a process handle with OpenProcess and then use
WaitSingleObject.

That's how you do it with the windows C APIs, either. Nim might provide
wrappers.

**Comment by Rummskartoffel** [comment]
Thanks! That looks reasonably simple.
I'm not aware of any wrappers in the standard library – though I haven't looked all that hard yet –, but I found a module a few days ago that might have it. I'll see if I can find it again.

**Comment by bovine3dom** [comment]
I think this issue blocks releasing the nim native messenger on Windows.

Because we can use platform-specific defaults we don't need to delay the Linux or Mac release.

**Comment by bovine3dom** [comment]
Added in #19
